[versions]
# Plugins
shadow = "9.6.1"
pluginYml = "0.9.0"
runPaper = "3.1.0"
axionRelease = "1.21.2"

#Dependencies
invui = "2.5.0"
paperApi = "26.2.build.+"
placeholderapi = "2.12.3"
astralib = "0.8.0-SNAPSHOT"
plan = "5.8.3638"
discordsrv = "1.30.5"
junitBom = "5.14.4"

[libraries]
invui = { module = "xyz.xenondevs.invui:invui", version.ref = "invui" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paperApi" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
astralib = { module = "de.unknowncity.astralib:astralib-paper-api", version.ref = "astralib" }
plan = { module = "com.github.plan-player-analytics:Plan", version.ref = "plan" }
discordsrv = { module = "com.discordsrv:discordsrv", version.ref = "discordsrv" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
plugin-yml-bukkit = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "pluginYml" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axionRelease" }
