# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Yasmp Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar

      - name: Determine Version
        id: determine_version
        run: |
          VERSION=$(./gradlew currentVersion -q -Prelease.quiet)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # GitHub secret token
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Git tag (for automatic releases)
          automatic_release_tag: ${{ steps.determine_version.outputs.version }}
          # Should this release be marked as a draft?
          draft: false # optional
          # Should this release be marked as a pre-release?
          prerelease: false # optional, default is true
          # Release title (for automatic releases)
          title: "Release ${{ steps.determine_version.outputs.version }}" # optional
          # Assets to upload to the release
          files: |
            build/libs/*.jar

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
